on: [push]
jobs:
  hello-test:
    runs-on: ubuntu-dotnet-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - run: echo All good!
      - run: which docker
      - run: ls cli.tests/bats/libs/bats
      - run: DOCKER_HOST=tcp://127.0.0.1:2375 docker build -t my-app .
  
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:10.0
    steps:
      - name: Check for dotnet sdk
        run: dotnet --list-sdks
  
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3

      # - name: Set up Docker Context for Buildx
      #   id: buildx-context
      #   run: |
      #     docker context create builders

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          endpoint: tcp://127.0.0.1:2375

      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: dug:latest