on: [push]
jobs:
  hello-test:
    runs-on: docker
    steps:
      - run: echo All good!
  
  build-docker:
    runs-on: docker
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Context for Buildx
        id: buildx-context
        run: |
          docker context create builders

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest
          endpoint: builders

      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: dug:latest