name: Publish

on:
  push:
    tags:
    - '[0-9]+\.[0-9]+\.[0-9]+'
    

env:
  DOCKER_HOST: tcp://127.0.0.1:2375
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

jobs:
  tests:
    runs-on: ubuntu-dotnet-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - run: dotnet --list-sdks
      - run: dotnet publish -r linux-x64 -c Release -p:PublishSingleFile=true -p:PublishReadyToRun=true --self-contained true -o publish ./cli
      - run: ./cli.tests/bats/run.sh
      - run: docker build -t my-app .
  
  publish:
    runs-on: ubuntu-dotnet-24.04
    needs: tests
    steps:
      - uses: actions/checkout@v4
      - run: echo "Publishing tagged version ${{forgejo.ref_name}}"
      - run: sed -i 's~<Version>0.0.1</Version>~<Version>${{forgejo.ref_name}}</Version>~' ./cli/dug.csproj #Set the Version in the csproj, its the only way to get the packaging tools to respect the version.
      - run: cat ./cli/dug.csproj
      - run: dotnet publish -r linux-x64 -c Release -p:PublishSingleFile=true -p:PublishReadyToRun=true --self-contained true -o publish ./cli

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.UNFRL_DOCKERHUB_USER }}
          password: ${{ secrets.UNFRL_DOCKERHUB_PAT }}
      
      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: unfrl/dug:${{forgejo.ref_name}},unfrl/dug:latest

  # TODO: Maybe only ACTUALLY publish if the tag is associated with a commit on main. tags dont give you that context so you might have to dig a little. Maybe uneccessary

  # container-test-job:
  #   runs-on: ubuntu-latest
  #   container:
  #     image: mcr.microsoft.com/dotnet/sdk:10.0
  #   steps:
  #     - name: Check for dotnet sdk
  #       run: dotnet --list-sdks
  
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3

      # - name: Set up Docker Context for Buildx
      #   id: buildx-context
      #   run: |
      #     docker context create builders

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          endpoint: tcp://127.0.0.1:2375

      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: dug:latest