name: Publish

on:
  push:
    branches:
      - '**'
    tags:
      - '[0-9]+\.[0-9]+\.[0-9]+'
    

env:
  DOCKER_HOST: tcp://127.0.0.1:2375
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

jobs:
  build:
    runs-on: ubuntu-dotnet-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Set version if tag
        if: ${{forgejo.ref_type == 'tag'}}
        run: |
          echo "Building tagged version ${{forgejo.ref_name}}"
          sed -i 's~<Version>0.0.1</Version>~<Version>${{forgejo.ref_name}}</Version>~' ./cli/dug.csproj #Set the Version in the csproj, its the only way to get the packaging tools to respect the version.
          cat ./cli/dug.csproj
        
      - name: Build binaries
        run: |
          dotnet publish -r linux-x64 -c Release -p:PublishSingleFile=true -p:PublishReadyToRun=true --self-contained true -o publish ./cli
          mv ./publish/dug ./publish/dug-linux-x64 #Rename the binary to its architecture type
          dotnet publish -r linux-arm64 -c Release -p:PublishSingleFile=true -p:PublishReadyToRun=true --self-contained true -o publish ./cli
          mv ./publish/dug ./publish/dug-linux-arm64 #Rename the binary to its architecture type
          dotnet publish -r osx-x64 -c Release -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true --self-contained true -o publish ./cli
          mv ./publish/dug ./publish/dug-osx-x64 #Rename the binary to its architecture type
          dotnet publish -r win-x64 -c Release -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true --self-contained true -o publish ./cli

        # This is where we would want to add steps to build the deb/rpm/pkg/tar/etc
      
      - uses: https://github.com/christopherHX/gitea-upload-artifact@v4
        with:
          name: dug-${{forgejo.run_id}}
          path: publish

  test:
    runs-on: ubuntu-dotnet-24.04
    needs: build
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - uses: https://github.com/christopherHX/gitea-download-artifact@v4
        with:
          name: dug-${{forgejo.run_id}}
          path: publish
      
      - name: Ensure binaries are executable
        run: |
          chmod -R +x publish/
          ls -lha publish

      - name: Run BATS tests
        shell: bash
        run: ./cli.tests/bats/run.sh
  
  publish:
    runs-on: ubuntu-dotnet-24.04
    needs: test
    if: ${{forgejo.ref_type == 'tag'}}
    steps:
      - uses: actions/checkout@v4
      - uses: https://github.com/christopherHX/gitea-download-artifact@v4
        with:
          name: dug-${{forgejo.run_id}}
          path: publish

      - name: Ensure binaries are executable
        run: |
          chmod -R +x publish/
          ls -lha publish

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.UNFRL_DOCKERHUB_USER }}
          password: ${{ secrets.UNFRL_DOCKERHUB_PAT }}
      
      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: unfrl/dug:${{forgejo.ref_name}},unfrl/dug:latest

  # TODO: Maybe only ACTUALLY publish if the tag is associated with a commit on main. tags dont give you that context so you might have to dig a little. Maybe uneccessary

  # container-test-job:
  #   runs-on: ubuntu-latest
  #   container:
  #     image: mcr.microsoft.com/dotnet/sdk:10.0
  #   steps:
  #     - name: Check for dotnet sdk
  #       run: dotnet --list-sdks
  
  # build-docker:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3
  #       with:
  #         endpoint: tcp://127.0.0.1:2375

  #     - name: Build
  #       uses: docker/build-push-action@v6
  #       with:
  #         context: .
  #         push: false
  #         tags: dug:latest