name: unfrl-dug # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: 0.0.1 # just for humans, typically '1.2+git' or '1.3.2'
summary: A powerful DNS progagation checker that can output in a variety of formats. # 79 char long summary
description: |
  A powerful global DNS progagation checker that can output in a variety of formats.
  The goal of dug is to make it easy to check the propagation of DNS records. It is also capable of providing templated output that can be used in scripts for things like monitoring.
  For detailed documentation check out dug.unfrl.com

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  unfrl-dug:
    command: ./dug
    plugs:
      - home
      - network
parts:
  dug:
    plugin: dotnet
    dotnet-version: 7.0
    dotnet-runtime-version: '7.0.0'
    source: .
    source-type: local
    override-build: |
      dotnet build -c Release
      dotnet publish -r linux-x64 -c Release -p:PublishSingleFile=true -p:PublishReadyToRun=true --self-contained true -o $SNAPCRAFT_PART_INSTALL
      chmod 0755 $SNAPCRAFT_PART_INSTALL/dug
