// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dug.Data;

namespace dug.Migrations
{
    [DbContext(typeof(DugContext))]
    partial class DugContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("dug.Data.Models.DnsServer", b =>
                {
                    b.Property<Guid>("DnsServerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryCode")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DNSSEC")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Reliability")
                        .HasColumnType("REAL");

                    b.HasKey("DnsServerId");

                    b.HasIndex("CountryCode")
                        .IsUnique();

                    b.HasIndex("IPAddress")
                        .IsUnique();

                    b.ToTable("DnsServers");
                });
#pragma warning restore 612, 618
        }
    }
}
