//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dug.i18n {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class dug {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal dug() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("dug.i18n.dug", typeof(dug).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string HT_Enable_Verbose_Output {
            get {
                return ResourceManager.GetString("HT_Enable_Verbose_Output", resourceCulture);
            }
        }
        
        public static string HT_Parallel {
            get {
                return ResourceManager.GetString("HT_Parallel", resourceCulture);
            }
        }
        
        public static string HT_Retries {
            get {
                return ResourceManager.GetString("HT_Retries", resourceCulture);
            }
        }
        
        public static string HT_Timeout {
            get {
                return ResourceManager.GetString("HT_Timeout", resourceCulture);
            }
        }
        
        public static string HT_Run {
            get {
                return ResourceManager.GetString("HT_Run", resourceCulture);
            }
        }
        
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        public static string EX_Specify_Query_Types {
            get {
                return ResourceManager.GetString("EX_Specify_Query_Types", resourceCulture);
            }
        }
        
        public static string EX_Specify_Continents {
            get {
                return ResourceManager.GetString("EX_Specify_Continents", resourceCulture);
            }
        }
        
        public static string EX_Query_Reliable_On_Continents {
            get {
                return ResourceManager.GetString("EX_Query_Reliable_On_Continents", resourceCulture);
            }
        }
        
        public static string EX_Json_Fields_Output {
            get {
                return ResourceManager.GetString("EX_Json_Fields_Output", resourceCulture);
            }
        }
        
        public static string HT_Run_Hostname {
            get {
                return ResourceManager.GetString("HT_Run_Hostname", resourceCulture);
            }
        }
        
        public static string HT_Run_Custom_Server_File {
            get {
                return ResourceManager.GetString("HT_Run_Custom_Server_File", resourceCulture);
            }
        }
        
        public static string HT_Run_Servers {
            get {
                return ResourceManager.GetString("HT_Run_Servers", resourceCulture);
            }
        }
        
        public static string ER_Run_Server_Parse {
            get {
                return ResourceManager.GetString("ER_Run_Server_Parse", resourceCulture);
            }
        }
        
        public static string HT_Run_Server_Count {
            get {
                return ResourceManager.GetString("HT_Run_Server_Count", resourceCulture);
            }
        }
        
        public static string HT_Run_Continents {
            get {
                return ResourceManager.GetString("HT_Run_Continents", resourceCulture);
            }
        }
        
        public static string ER_Run_Inavlid_Continent {
            get {
                return ResourceManager.GetString("ER_Run_Inavlid_Continent", resourceCulture);
            }
        }
        
        public static string HT_Run_Query_Types {
            get {
                return ResourceManager.GetString("HT_Run_Query_Types", resourceCulture);
            }
        }
        
        public static string ER_Run_Invalid_Query_Type {
            get {
                return ResourceManager.GetString("ER_Run_Invalid_Query_Type", resourceCulture);
            }
        }
        
        public static string HT_Run_Multiple_Server_Sources {
            get {
                return ResourceManager.GetString("HT_Run_Multiple_Server_Sources", resourceCulture);
            }
        }
        
        public static string HT_Run_Data_Columns {
            get {
                return ResourceManager.GetString("HT_Run_Data_Columns", resourceCulture);
            }
        }
        
        public static string ER_Run_Data_Columns_Without_Server_File {
            get {
                return ResourceManager.GetString("ER_Run_Data_Columns_Without_Server_File", resourceCulture);
            }
        }
        
        public static string ER_Run_Unable_Parse_Data_Column_Header {
            get {
                return ResourceManager.GetString("ER_Run_Unable_Parse_Data_Column_Header", resourceCulture);
            }
        }
        
        public static string HT_Run_Data_Headers_Present {
            get {
                return ResourceManager.GetString("HT_Run_Data_Headers_Present", resourceCulture);
            }
        }
        
        public static string ER_Run_Data_Headers_Present_Requires_Data_Columns {
            get {
                return ResourceManager.GetString("ER_Run_Data_Headers_Present_Requires_Data_Columns", resourceCulture);
            }
        }
        
        public static string HT_Run_Data_Separator {
            get {
                return ResourceManager.GetString("HT_Run_Data_Separator", resourceCulture);
            }
        }
        
        public static string ER_Run_Data_Separator_Requires_Data_Columns {
            get {
                return ResourceManager.GetString("ER_Run_Data_Separator_Requires_Data_Columns", resourceCulture);
            }
        }
        
        public static string HT_Run_Template {
            get {
                return ResourceManager.GetString("HT_Run_Template", resourceCulture);
            }
        }
        
        public static string ER_Run_Unable_Parse_Template_Header {
            get {
                return ResourceManager.GetString("ER_Run_Unable_Parse_Template_Header", resourceCulture);
            }
        }
        
        public static string HT_Run_Output_Format {
            get {
                return ResourceManager.GetString("HT_Run_Output_Format", resourceCulture);
            }
        }
        
        public static string ER_Run_Output_Format_Requires_Template {
            get {
                return ResourceManager.GetString("ER_Run_Output_Format_Requires_Template", resourceCulture);
            }
        }
        
        public static string HT_Run_Table_Detail_Level {
            get {
                return ResourceManager.GetString("HT_Run_Table_Detail_Level", resourceCulture);
            }
        }
        
        public static string ER_Run_Table_Detail_Out_Of_Range {
            get {
                return ResourceManager.GetString("ER_Run_Table_Detail_Out_Of_Range", resourceCulture);
            }
        }
        
        public static string HT_Update {
            get {
                return ResourceManager.GetString("HT_Update", resourceCulture);
            }
        }
        
        public static string EX_Overwrite {
            get {
                return ResourceManager.GetString("EX_Overwrite", resourceCulture);
            }
        }
        
        public static string EX_Import_Servers {
            get {
                return ResourceManager.GetString("EX_Import_Servers", resourceCulture);
            }
        }
        
        public static string EX_Import_And_Overwrite_Servers {
            get {
                return ResourceManager.GetString("EX_Import_And_Overwrite_Servers", resourceCulture);
            }
        }
        
        public static string EX_Remote_Import_And_Update {
            get {
                return ResourceManager.GetString("EX_Remote_Import_And_Update", resourceCulture);
            }
        }
        
        public static string EX_Remote_Import_And_Update_Prune {
            get {
                return ResourceManager.GetString("EX_Remote_Import_And_Update_Prune", resourceCulture);
            }
        }
        
        public static string EX_Update_Reliability_Prune_2_Retries {
            get {
                return ResourceManager.GetString("EX_Update_Reliability_Prune_2_Retries", resourceCulture);
            }
        }
        
        public static string HT_Update_Custom_Server_File {
            get {
                return ResourceManager.GetString("HT_Update_Custom_Server_File", resourceCulture);
            }
        }
        
        public static string HT_Update_Servers {
            get {
                return ResourceManager.GetString("HT_Update_Servers", resourceCulture);
            }
        }
        
        public static string ER_Update_Server_Parse {
            get {
                return ResourceManager.GetString("ER_Update_Server_Parse", resourceCulture);
            }
        }
        
        public static string HT_Update_Overwrite {
            get {
                return ResourceManager.GetString("HT_Update_Overwrite", resourceCulture);
            }
        }
        
        public static string HT_Update_Reliability {
            get {
                return ResourceManager.GetString("HT_Update_Reliability", resourceCulture);
            }
        }
        
        public static string HT_Update_Reliability_Only {
            get {
                return ResourceManager.GetString("HT_Update_Reliability_Only", resourceCulture);
            }
        }
        
        public static string ER_Update_Reliability_Only_Requires_Reliability {
            get {
                return ResourceManager.GetString("ER_Update_Reliability_Only_Requires_Reliability", resourceCulture);
            }
        }
        
        public static string HT_Update_Update_URL {
            get {
                return ResourceManager.GetString("HT_Update_Update_URL", resourceCulture);
            }
        }
        
        public static string ER_Update_Update_URL_Requires_File_Or_Servers {
            get {
                return ResourceManager.GetString("ER_Update_Update_URL_Requires_File_Or_Servers", resourceCulture);
            }
        }
        
        public static string ER_Update_Update_URL_Requires_Data_Columns {
            get {
                return ResourceManager.GetString("ER_Update_Update_URL_Requires_Data_Columns", resourceCulture);
            }
        }
        
        public static string ER_Update_Unable_Parse_Update_URL {
            get {
                return ResourceManager.GetString("ER_Update_Unable_Parse_Update_URL", resourceCulture);
            }
        }
        
        public static string HT_Update_Data_Columns {
            get {
                return ResourceManager.GetString("HT_Update_Data_Columns", resourceCulture);
            }
        }
        
        public static string ER_Update_Unable_Parse_Data_Column_Header {
            get {
                return ResourceManager.GetString("ER_Update_Unable_Parse_Data_Column_Header", resourceCulture);
            }
        }
        
        public static string HT_Update_Data_Headers_Present {
            get {
                return ResourceManager.GetString("HT_Update_Data_Headers_Present", resourceCulture);
            }
        }
        
        public static string ER_Update_Data_Headers_Present_Requires_Data_Columns {
            get {
                return ResourceManager.GetString("ER_Update_Data_Headers_Present_Requires_Data_Columns", resourceCulture);
            }
        }
        
        public static string HT_Update_Data_Separator {
            get {
                return ResourceManager.GetString("HT_Update_Data_Separator", resourceCulture);
            }
        }
        
        public static string ER_Update_Data_Separator_Requires_Data_Columns {
            get {
                return ResourceManager.GetString("ER_Update_Data_Separator_Requires_Data_Columns", resourceCulture);
            }
        }
        
        public static string Output_Retrieved_X_Servers_From_Remote_X {
            get {
                return ResourceManager.GetString("Output_Retrieved_X_Servers_From_Remote_X", resourceCulture);
            }
        }
        
        public static string Output_Loaded_X_Servers_From_X {
            get {
                return ResourceManager.GetString("Output_Loaded_X_Servers_From_X", resourceCulture);
            }
        }
        
        public static string Output_Added_X_Servers_From_X {
            get {
                return ResourceManager.GetString("Output_Added_X_Servers_From_X", resourceCulture);
            }
        }
        
        public static string Output_Added_X_Servers {
            get {
                return ResourceManager.GetString("Output_Added_X_Servers", resourceCulture);
            }
        }
        
        public static string Output_Added_X_Servers_Provided_Already_Present {
            get {
                return ResourceManager.GetString("Output_Added_X_Servers_Provided_Already_Present", resourceCulture);
            }
        }
        
        public static string Output_Overwritting_X_With_X_Specified_Servers {
            get {
                return ResourceManager.GetString("Output_Overwritting_X_With_X_Specified_Servers", resourceCulture);
            }
        }
        
        public static string Output_Loaded_X_Servers_From_Included_Source {
            get {
                return ResourceManager.GetString("Output_Loaded_X_Servers_From_Included_Source", resourceCulture);
            }
        }
        
        public static string ER_File_Not_Found {
            get {
                return ResourceManager.GetString("ER_File_Not_Found", resourceCulture);
            }
        }
        
        public static string ER_Must_Be_Between_0_1 {
            get {
                return ResourceManager.GetString("ER_Must_Be_Between_0_1", resourceCulture);
            }
        }
        
        public static string Output_Pruning_Because_Failed {
            get {
                return ResourceManager.GetString("Output_Pruning_Because_Failed", resourceCulture);
            }
        }
        
        public static string ER_Unable_To_Get_Value_From_Header_X_Expected_At_Index_X {
            get {
                return ResourceManager.GetString("ER_Unable_To_Get_Value_From_Header_X_Expected_At_Index_X", resourceCulture);
            }
        }
        
        public static string ER_Unable_Set_Field_X_To_Value_X {
            get {
                return ResourceManager.GetString("ER_Unable_Set_Field_X_To_Value_X", resourceCulture);
            }
        }
        
        public static string Table_Server_Info {
            get {
                return ResourceManager.GetString("Table_Server_Info", resourceCulture);
            }
        }
        
        public static string Table_Results {
            get {
                return ResourceManager.GetString("Table_Results", resourceCulture);
            }
        }
        
        public static string Table_Reliability {
            get {
                return ResourceManager.GetString("Table_Reliability", resourceCulture);
            }
        }
        
        public static string Table_Record_Type {
            get {
                return ResourceManager.GetString("Table_Record_Type", resourceCulture);
            }
        }
        
        public static string Table_Value {
            get {
                return ResourceManager.GetString("Table_Value", resourceCulture);
            }
        }
        
        public static string Table_Continent_Consensus {
            get {
                return ResourceManager.GetString("Table_Continent_Consensus", resourceCulture);
            }
        }
        
        public static string Table_Records_For {
            get {
                return ResourceManager.GetString("Table_Records_For", resourceCulture);
            }
        }
        
        public static string Table_Argument {
            get {
                return ResourceManager.GetString("Table_Argument", resourceCulture);
            }
        }
        
        public static string Table_Description {
            get {
                return ResourceManager.GetString("Table_Description", resourceCulture);
            }
        }
        
        public static string ER_Unable_Render_Results_In_Format {
            get {
                return ResourceManager.GetString("ER_Unable_Render_Results_In_Format", resourceCulture);
            }
        }
        
        public static string ER_Unable_Resolve_Header {
            get {
                return ResourceManager.GetString("ER_Unable_Resolve_Header", resourceCulture);
            }
        }
        
        public static string Output_Start_Query {
            get {
                return ResourceManager.GetString("Output_Start_Query", resourceCulture);
            }
        }
        
        public static string Output_Finish_Query {
            get {
                return ResourceManager.GetString("Output_Finish_Query", resourceCulture);
            }
        }
        
        public static string Output_Timeout {
            get {
                return ResourceManager.GetString("Output_Timeout", resourceCulture);
            }
        }
        
        public static string Output_Error {
            get {
                return ResourceManager.GetString("Output_Error", resourceCulture);
            }
        }
        
        public static string Output_Unhandled_Error {
            get {
                return ResourceManager.GetString("Output_Unhandled_Error", resourceCulture);
            }
        }
        
        public static string Output_Animation_Disabled {
            get {
                return ResourceManager.GetString("Output_Animation_Disabled", resourceCulture);
            }
        }
        
        public static string Output_Connection_Timeout {
            get {
                return ResourceManager.GetString("Output_Connection_Timeout", resourceCulture);
            }
        }
        
        public static string Table_Overall {
            get {
                return ResourceManager.GetString("Table_Overall", resourceCulture);
            }
        }
        
        public static string Table_Out_OF {
            get {
                return ResourceManager.GetString("Table_Out_OF", resourceCulture);
            }
        }
        
        public static string ER_Hostname_Missing {
            get {
                return ResourceManager.GetString("ER_Hostname_Missing", resourceCulture);
            }
        }
        
        public static string Output_Verbose_Enabled {
            get {
                return ResourceManager.GetString("Output_Verbose_Enabled", resourceCulture);
            }
        }
        
        public static string ER_Specified_File_Not_Found {
            get {
                return ResourceManager.GetString("ER_Specified_File_Not_Found", resourceCulture);
            }
        }
        
        public static string ER_Unable_To_Parse_File {
            get {
                return ResourceManager.GetString("ER_Unable_To_Parse_File", resourceCulture);
            }
        }
        
        public static string Output_Servers_To_Use {
            get {
                return ResourceManager.GetString("Output_Servers_To_Use", resourceCulture);
            }
        }
        
        public static string Output_Testing_Server_Responses {
            get {
                return ResourceManager.GetString("Output_Testing_Server_Responses", resourceCulture);
            }
        }
        
        public static string Output_Testing_Server_Responses_Finished {
            get {
                return ResourceManager.GetString("Output_Testing_Server_Responses_Finished", resourceCulture);
            }
        }
        
        public static string Africa {
            get {
                return ResourceManager.GetString("Africa", resourceCulture);
            }
        }
        
        public static string South_America {
            get {
                return ResourceManager.GetString("South_America", resourceCulture);
            }
        }
        
        public static string North_America {
            get {
                return ResourceManager.GetString("North_America", resourceCulture);
            }
        }
        
        public static string Oceania {
            get {
                return ResourceManager.GetString("Oceania", resourceCulture);
            }
        }
        
        public static string Asia {
            get {
                return ResourceManager.GetString("Asia", resourceCulture);
            }
        }
        
        public static string Europe {
            get {
                return ResourceManager.GetString("Europe", resourceCulture);
            }
        }
        
        public static string Antarctica {
            get {
                return ResourceManager.GetString("Antarctica", resourceCulture);
            }
        }
        
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        public static string HT_Run_Watch {
            get {
                return ResourceManager.GetString("HT_Run_Watch", resourceCulture);
            }
        }
        
        public static string ER_Run_Output_Format_Cannot_Be_Used_With_Watch {
            get {
                return ResourceManager.GetString("ER_Run_Output_Format_Cannot_Be_Used_With_Watch", resourceCulture);
            }
        }
        
        public static string ER_Run_Watch_Out_Of_Range {
            get {
                return ResourceManager.GetString("ER_Run_Watch_Out_Of_Range", resourceCulture);
            }
        }
        
        public static string Output_Scan_Every {
            get {
                return ResourceManager.GetString("Output_Scan_Every", resourceCulture);
            }
        }
    }
}
